name: flutter_volume_controller
description: A Flutter plugin to control system volume and listen for volume changes on different platforms.
version: 1.3.2
homepage: https://github.com/yosemiteyss/flutter_volume_controller

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.yosemiteyss.flutter_volume_controller
        pluginClass: FlutterVolumeControllerPlugin
      ios:
        pluginClass: FlutterVolumeControllerPlugin
      macos:
        pluginClass: FlutterVolumeControllerPlugin
      windows:
        pluginClass: FlutterVolumeControllerPluginCApi
      linux:
        pluginClass: FlutterVolumeControllerPlugin
